name=ESP32-Metaheuristics
version=0.1.0
author=Neil Otniel Moreno Rivera <neilotniel@gmail.com>
maintainer=Neil Otniel Moreno Rivera <neilotniel@gmail.com>
sentence=Algoritmos bioinspirados y evolutivos (GA, DE, PSO, ABC, GWO, WOA) para ESP32.
paragraph=Colección de metaheurísticos de optimización con una interfaz común basada en funciones objetivo genéricas. Pensada para ESP32 pero portable a otras placas Arduino con std::vector y std::function disponibles.
category=Data Processing
url=https://github.com/VagrantTrack149/ESP32-Metaheuristics
architectures=esp32,*
includes=ESP32-Metaheuristics.h
depends=